package:
  name: torcyx
  version: "0.1"

source:
  git_url: https://github.com/kaihsin/Torcyx.git

build:
  number: 0


requirements:
  build:
    - python {{ python }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cytnx
    - pytorch >=1.6
    - torchvision
    - cpuonly  # [linux]
    - setuptools
    - cmake  
    - pybind11 

  host:
    - python 
    - cytnx
    - pytorch >=1.6
    - cpuonly # [linux]
    - torchvision
    - setuptools
    - cmake  
    - pybind11 


  run:
    - python
    - cytnx
    - pytorch >=1.6
    - cpuonly # [linux]
    - torchvision
    - setuptools
    - cmake  
    - pybind11 

about:
